# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProjectTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_projectTest(self):
    self.driver.get("http://localhost:8080/Avi_Eden_Noam_May/Project.jsp")
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Avi")
    self.driver.find_element(By.NAME, "action").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Name submitted: Avi"
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Eden")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Hello, Eden!"
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Noam")
    self.driver.find_element(By.NAME, "action").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Name submitted: Noam"
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("May")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h3").text == "Hello, May!"
  
